# Generated by Django 3.2.9 on 2021-11-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='number of appointment')),
                ('user_id', models.IntegerField(verbose_name="user's id")),
                ('doctor_fullname', models.CharField(max_length=256, verbose_name='doctor')),
                ('start_datetime', models.DateTimeField(verbose_name='doctor meeting start date and time')),
                ('end_datetime', models.DateTimeField(verbose_name='doctor meeting end date and time')),
            ],
        ),
    ]
